### ISSUE TITLE
Search page "expand" button on map does not open the mapview page.

### ISSUE THREAD

**Issue by alecclyde** [alecclyde/TheLoop#166]
Error received (would work on this now but I am prioritizing Google play publishing over this for now, unless someone else takes it): 

"TypeError: undefined is not an object (evaluating 'props.user.location')

This error is located at:
    in mapView (created by Connect(mapView))
    in Connect(mapView) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)..... "

**Comment by NedacNostrebor** [comment]
Fixed on my branch, I'll push in a bit
