### ISSUE TITLE
On android, date and time pickers do not have "ok" or "cancel" buttons.

### ISSUE THREAD

**Issue by alecclyde** [alecclyde/TheLoop#90]
It might be white text on white background issue.

**Comment by alecclyde** [comment]
Bump?

**Comment by airgo32** [comment]
I did some digging for about an hour tonight. Apparently, [this is not a new issue](https://github.com/react-native-datetimepicker/datetimepicker/issues/524). 

I did some digging and found some leads, but I haven't figured anything out yet, at least for the spinner style. I found [this possible solution](https://github.com/react-native-datetimepicker/datetimepicker/issues/20#issuecomment-545527682) and [this other possible piece](https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/106#issuecomment-486109312), but I haven't figured out how to get them to work together.

For now, setting it to the default styles on Android makes the buttons appear.
